version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  backend:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.9
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pipenv run python manage.py test 
  frontend:
    working_directory: ~/frontend
    docker:
      - image: circleci/node@3.0.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          command: |
            - node/test
workflows:
  testing:
    jobs:
      - backend
      - frontend